import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppNavbar from "./components/AppNavbar";
import "./scss/layout.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <div className="layout">
        <body className={inter.className}>
          <AppNavbar />
          {children}
        </body>
      </div>
    </html>
  );
}
